#!/bin/sh

# In this directoy run 
# sh ./INSTALL
# That is all

grep -q "CWD Correct" INSTALL || exit 1
mkdir -p $HOME/bin
cp bin/my-helper $HOME/bin/
chmod 0700 $HOME/bin/my-helper
git config --global credential.helper $HOME/bin/my-helper
git config --global credential.useHttpPath true
